#!/bin/bash

show_progress() {
  local step=$1
  local total=7
  local progress=$((step * 100 / total))
  local bar=$(printf "%0.s#" $(seq 1 $((progress / 10))))
  printf "\rInstalando: [%-10s] %d%%" "$bar" "$progress"
  sleep 1
}

echo "Iniciando configuração do servidor MagnumSSH..."
step=0

show_progress $((++step))
bash <(wget -qO- https://raw.githubusercontent.com/Sidney2025340/MagnumSSH/refs/heads/main/install.sh) > /dev/null 2>&1

show_progress $((++step))
/opt/magnumssh/connectionsmanager --conn proxy --enable-port 80 > /dev/null 2>&1

show_progress $((++step))
/opt/magnumssh/connectionsmanager --conn proxy --enable-port 8080 > /dev/null 2>&1

show_progress $((++step))
/opt/magnumssh/connectionsmanager --conn sslproxy --enable-port 443 > /dev/null 2>&1

show_progress $((++step))
for port in 7100 7200 7300 7400 7500 7600; do
  /opt/magnumssh/connectionsmanager --conn badvpn --enable-port $port > /dev/null 2>&1
done

show_progress $((++step))
timedatectl set-timezone America/Sao_Paulo > /dev/null 2>&1

show_progress $((++step))
echo 'MaxStartups 2000:10:2000' >> /etc/ssh/sshd_config && service ssh restart > /dev/null 2>&1

show_progress $step
echo -e "\n✅ Instalação e configuração concluída com sucesso!"
